### ISSUE TITLE
Hostname is still `example.com` after update to `nginx.conf`

### ISSUE THREAD

**Issue by haze** [milesmcc/shynet#173] opened 2021-09-25 10:32 UTC
I am running on a non-standard docker environment (docker-compose w/ lima & containerd), however I've ventured into the `shynet_webserver` container using `lima nerdctl exec -it shynet_webserver /bin/sh` and inspected the `nginx.conf` that is copied over to `/etc/nginx/conf.d/default.conf` and verified that the hostname in both files points to the host name I want: `analytics.haze.cool`. Despite these modifications, the hostname on the site is still broadcasted as `example.com`. Am I missing a crucial step somewhere? (I've been following the `docker-compose` setup in `GUIDE.md`)

**Comment by milesmcc** [comment] 2021-09-25 20:20
This sounds like a whitelabel issue, not a hostname issue. (I know it's a bit unintuitive.) Did you complete this step?

> Set the whitelabel of your Shynet instance by running docker run `--env-file=<your env file> milesmcc/shynet:latest ./manage.py whitelabel <whitelabel>`. While this setting doesn't affect any core operations of Shynet, it lets you rename Shynet to whatever you want. (Example whitelabels: "My Shynet Instance" or "Acme Analytics".)

I'm going to tentatively close this, but feel free to follow up if you're still running into issues.

**Closed by milesmcc** 2021-09-25 20:20 UTC

**Comment by haze** [comment] 2021-09-26 20:03
```
 haze@Titanium.local 1ms ~/S/shynet lima nerdctl exec -it shynet_main ./manage.py whitelabel analytics.haze.cool
Successfully set the whitelabel to 'analytics.haze.cool'
```

I've ran this and the flavor text on the main page and the intro text still reads:
```
Welcome to example.com, a self-hosted analytics tool that's open source and privacy conscious. Powered by Shynet. View the source code.
```

I haven't looked into how the Django template works entirely, so I'm not sure if it's the white label or the nginx conf, but continuing onto the site, the instructions for which JS files to download, also include `example.com`

**Comment by haze** [comment] 2021-09-28 21:30
@milesmcc any thoughts?

**Comment by CasperVerswijvelt** [comment] 2021-09-28 21:37
@haze i think the issue is maybe with the hostname and not the whitelabel like miles said. I see that your instance is running 0.10.0, try using the docker 'edge' tag to use version 0.11.0. In that version the hostname is no longer set via configuration, but is based on the request headers.

**Comment by haze** [comment] 2021-09-28 22:26
@CasperVerswijvelt Ah! You were right! I was using the `latest` tag which is specified in the `docker-compose.yml` which didn't quite sync up with the wiki. Thanks so much.

**Comment by CasperVerswijvelt** [comment] 2021-09-29 06:16
@haze yeah something probably went wrong with the automated docker build and the GitHub tag didn't succesfully build and push a tag to dockerhub (#170 )
